# Site settings
author: Clyde  Griffin
title: Why I decide to study software engineering?
header-img: img/home-bg.png
email: deezy13@gmail.com
copyright_name: Clyde  Griffin
description: > # this means to ignore newlines until "baseurl:"
  Posted by Clyde Griffin on February 3, 2020
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  deezy136

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
